config/routes.rb
Rails.application.routes.draw do
  get 'publics/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'publics#index'
  devise_scope :user do
    authenticated :user do
      resources :products
      resources :suppliers
      resources :customers
      resources :purchases
      resources :sales
      resources :managers
      get 'adds/index'
      get 'updates/index'
      get 'updates/list_s'
      get 'updates/list_c'
      get 'updates/list_p'
      root 'adds#index', as: :authenticated_user_root
    end
  end
  devise_scope :manager do
    authenticated :manager do
      resources :products, :only => [:update, :show]
      resources :suppliers, :only => [:show]
      resources :customers, :only => [:show]
      get 'balances/index'
      get 'summaries/list'
      get 'summaries/prod'
      get 'summaries/index'
      resources :inflows
      resources :outflows
      # get 'inflows/new'
      # get 'inflows/index'
      # get 'inflows/show'
      # get 'inflows/update_products', as: 'update_products'
      # get 'inflows/_product'
      root 'balances#index', as: :authenticated_manager_root
    end
  end
  devise_scope :purchase do
    authenticated :purchase do
      get 'reorders/index'
      get 'reorders/reorder'
      get 'summaries/list'
      get 'summaries/prod'
      get 'summaries/index'
      resources :inflows, :only => [:show]
      resources :outflows, :only => [:show]
      resources :products
      resources :suppliers, :only => [:show]
      root 'reorders#index', as: :authenticated_purchase_root
    end
  end
  
  devise_scope :sale do
    authenticated :sale do
      resources :orders
      get 'orders/new'
      get 'reminders/index'
      get 'summaries/list'
      get 'summaries/prod'
      get 'summaries/index'
      root 'orders#new', as: :authenticated_sale_root
    end
  end
  devise_for :users
  devise_for :managers
  devise_for :purchases
  devise_for :sales
  root 'publics#index'
#   devise_for :users, controllers: { registrations: "registrations"}
end

app/models/customer.rb
class Customer < ApplicationRecord
end

app/models/inflow.rb
class Inflow < ApplicationRecord
    has_many :products, through: :inflow_product_quantities
    has_many :inflow_product_quantities

    accepts_nested_attributes_for :inflow_product_quantities
    accepts_nested_attributes_for :products
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :user
  has_many :inflows
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :products, through: :order_product_quantities
  has_many :order_product_quantities
  belongs_to :customer

  accepts_nested_attributes_for :order_product_quantities
  accepts_nested_attributes_for :products
end

app/models/outflow.rb
class Outflow < ApplicationRecord
    has_many :products, through: :outflow_product_quantities
    has_many :outflow_product_quantities

    accepts_nested_attributes_for :outflow_product_quantities
    accepts_nested_attributes_for :products
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :supplier
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :user
  has_many :products
end

app/models/sale.rb
class Sale < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :user
end

app/models/supplier.rb
class Supplier < ApplicationRecord
    # belongs_to :product
    has_many :products
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :customers
  has_many :suppliers
  has_many :products
  has_many :purchases 
  has_many :sales 
  has_many :managers
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
    
  end
end

app/helpers/adds_helper.rb
module AddsHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/helpers/inflows_helper.rb
module InflowsHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/outflows_helper.rb
module OutflowsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/reorders_helper.rb
module ReordersHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/updates_helper.rb
module UpdatesHelper
end

app/views/publics/index.html.erb
<!-- <h1>Welcome to our Product System!</h1> -->


<div class="mainContainer">

<div class="row">
  <div class="col-md-5">
    <div class="logIn">
      <div class="row container">
        <h1>Sign in as Admin</h1>
      </div>
      
      <%= form_for(:user, :url => session_path(:user)) do |f| %>
      <div class="row container">
          <div class="col-md-1">
            <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
          </div>
          <div class="col-md-2">
            <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
          </div>
      </div>
      
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1" style="margin-top:10px">
          <%= f.submit 'Sign in', class: "btn btn-prmry btn-md" %>
        </div>
      </div>
      <div class="row container" style="margin-top:5px">
        <div class="col-md-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> 
          <br>
          <%= link_to "Forgot your password?", new_password_path(:user) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>

 

  <div class="col-md-5">
    <div class="logIn">
      <div class="row container">
        <h1>Sign in as Warehouse Manager</h1>
      </div>
        
      <%= form_for(:manager, :url => session_path(:manager)) do |f| %>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        </div>
        <div class="col-md-2">
          <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1" style="margin-top:10px">
          <%= f.submit 'Sign in', class: "btn btn-prmry btn-md" %>
        </div>
      </div>
      <div class="row container" style="margin-top:10px">
        <div class="col-md-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> 
          <br>
          <%= link_to "Forgot your password?", new_password_path(:manager) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  

  
  <div class="col-md-5">
    <div class="logIn">
      <div class="row container">
        <h1>Sign in as Purchasing </h1>
      </div>
        
      <%= form_for(:purchase, :url => session_path(:purchase)) do |f| %>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        </div>
        <div class="col-md-2">
          <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1" style="margin-top:10px">
          <%= f.submit 'Sign in', class: "btn btn-prmry btn-md" %>
        </div>
      </div>
      <div class="row container" style="margin-top:10px">
        <div class="col-md-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> 
          <br>
          <%= link_to "Forgot your password?", new_password_path(:purchase) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  

 
  <div class="col-md-5">
    <div class="logIn">
      <div class="row container">
        <h1>Sign in as Sales </h1>
      </div>
        
      <%= form_for(:sale, :url => session_path(:sale)) do |f| %>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
        </div>
        <div class="col-md-2">
          <%= f.text_field :email, class: "inputLogin", placeholder: "Email"%>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1">
          <span class="glyphicon glyphicon-lock" aria-hidden="true"></span>
        </div>
        <div class="col-md-1">
          <%= f.password_field :password, class: "inputLogin", placeholder: "Password" %>
        </div>
      </div>
      <div class="row container">
        <div class="col-md-1" style="margin-top:10px">
          <%= f.submit 'Sign in', class: "btn btn-prmry btn-md" %>
        </div>
      </div>
      <div class="row container" style="margin-top:10px">
        <div class="col-md-3">
          <%= f.check_box :remember_me %>
          <%= f.label :remember_me %> 
          <br>
          <%= link_to "Forgot your password?", new_password_path(:sale) %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>